# Generated by Django 3.1.5 on 2021-01-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210116_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='humedad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='luz',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='magnetico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='posicion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='temperatura',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='velocidad',
            field=models.CharField(max_length=50),
        ),
    ]
