# Generated by Django 3.1.5 on 2021-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210116_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosnumericos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
