# Generated by Django 3.1.5 on 2021-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_codigosnumericos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosnumericos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
