# Generated by Django 3.1.5 on 2021-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaPuerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximidad', models.IntegerField()),
                ('opticos', models.IntegerField()),
                ('contacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodigosNumericos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelGasolina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ultrasónicos', models.CharField(max_length=10)),
                ('Capacitivo', models.CharField(max_length=10)),
                ('Flotador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posicion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('magnetico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('velocidad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
