# Generated by Django 3.1.5 on 2021-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensoresApertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SensoresGas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SensoresTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
