# Generated by Django 3.1.5 on 2021-01-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoresapertura',
            name='apertura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensoresgas',
            name='gas_tipo',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='sensorestemp',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='sensoresapertura',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensoresgas',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensorestemp',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
